//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_table
    {
        public int Course_Id { get; set; }
        public string Course_Name { get; set; }
        public string Course_Description { get; set; }
        public Nullable<System.DateTime> Course_StartDate { get; set; }
        public string Course_Author { get; set; }
        public string Course_Duration { get; set; }
        public string Course_Difficulty { get; set; }
        public string credit_score { get; set; }
    }
}
